name = "tech"
account_id = "**********"
workers_dev = true
compatibility_date = "2024-07-11"
main = "index.js"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[route]
pattern = "**********"
custom_domain = true
